PUT http://localhost:5029/api/courses/1
Content-Type: application/json

{
  "id": 1,
  "code": "CS-101",
  "title": "Updated Title",
  "maxCapacity": 30,
  "enrollmentCount": 2,
  "links": []
}
###
POST http://localhost:5029/api/v2/transcripts?api-version=2.0
Content-Type: application/json
Idempotency-Key: 11111111-2222-3333-4444-555555555555

{
  "studentId": 1
}
###
POST http://localhost:5029/api/v2/transcripts?api-version=2.0
Content-Type: application/json
Idempotency-Key: 777777777-22222-444444-33333333333

{
  "studentId": 1
}
###

GET http://localhost:5029/api/v2/transcripts/c641532c3d7a/status?api-version=2.0
###
POST http://localhost:5029/api/v2/transcripts?api-version=2.0
Content-Type: application/json
Idempotency-Key: TRIGGER-NOW-100

{
  "studentId": 1
}